---
# tasks file for pvwa clean

- name: Clean Windows\\Temp Folder
  win_find:
    paths: "C:\\Windows\\Temp"
    patterns: ['PVWA*.*', 'InstallationAutomation*.*']
  register: files_to_delete

- win_file:
    path: "{{item.path}}"
    state: absent
  with_items: "{{ files_to_delete.files }}"

- name: Clean cred files
  win_file:
    path: "{{item}}"
    state: absent
  with_items:
    - "{{ pvwa_installation_path }}\\CredFiles\\appuser.ini"
    - "{{ pvwa_installation_path }}\\CredFiles\\gwuser.ini"

- name: clean run history
  win_regedit:
    path: 'HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\RunMRU'
    state: absent
    delete_key: yes

- name: clean event logs
- win_shell: |
    try {
      wevtutil el | ForEach-Object { wevtutil cl "$_" }
    } catch {
      Write-Output "Error occured: $error"
      exit 1
    }

- name: clean recycle bin
- win_shell: |
    try {
      $Recycler = (New-Object -ComObject Shell.Application).Namespace(0xa)
      $Recycler.items() | ForEach-Object { rm $_.path -Force -Recurse }
    } catch {
      Write-Output "Error occured: $error"
      exit 1
    }