---
# tasks file for pvwa clean

- name: Find files to delete in Windows Temp folder
  ansible.windows.win_find:
    paths: "C:\\Windows\\Temp"
    patterns: ['PVWA*.*', 'InstallationAutomation*.*']
  register: files_to_delete

- name: Clean Windows Temp Folder
  ansible.windows.win_file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ files_to_delete.files }}"

- name: Clean cred files
  ansible.windows.win_file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ pvwa_installation_path }}\\CredFiles\\appuser.ini"
    - "{{ pvwa_installation_path }}\\CredFiles\\gwuser.ini"

- name: Keep installation automation folder
  ansible.windows.win_copy:
    src: "{{ pvwa_installationautomation_folder }}"
    dest: "{{ pvwa_base_bin_drive }}\\Cyberark\\PVWA"
    remote_src: true

- name: Delete the deployment folder
  ansible.windows.win_file:
    path: "{{ pvwa_extract_folder }}"
    state: absent

###############################

- name: Set CyberArk Scheduled Tasks Service Startup Mode to Manual
  ansible.windows.win_service:
    name: CyberArk Scheduled Tasks
    start_mode: manual
    state: stopped

- name: Stop PVWA application pool
  community.windows.win_iis_webapppool:
    name: PasswordVaultWebAccessPool
    state: stopped

- name: Create Deployment Folders
  ansible.windows.win_file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "C:\\CyberArk"
    - "C:\\CyberArk\\Deployment"
    - "C:\\CyberArk\\Deployment\\Logs"

- name: Copy PS1 scripts - AWS
  ansible.windows.win_copy:
    src: "files/aws/{{ item }}"
    dest: C:\CyberArk\Deployment\
  with_items:
    - UserDataScript.ps1
    - PVWARegistration.ps1
    - PVWAConfiguration.ps1
    - CloudWatch.ps1
    - Common.ps1
    - ../CreateSelfCertAndBind.ps1
  when: platform == 'aws'

- name: Copy PS1 scripts - Azure
  ansible.windows.win_copy:
    src: "files/CreateSelfCertAndBind.ps1"
    dest: "C:\\CyberArk\\"
  when: platform == 'azure'

- name: Copy CloudWatch Json
  ansible.windows.win_copy:
    src: "files/aws/AWS.EC2.Windows.CloudWatch.json"
    dest: "C:\\Program Files\\Amazon\\SSM\\Plugins\\awsCloudWatch\\"
  when: platform == 'aws'
