---
# tasks file for pvwa_validateparameters

- name: check EULA is accepted
  fail:
    msg: "You must accept EULA to start the playbook"
  when: (accept_eula|type_debug != 'bool' and accept_eula|lower != "yes") or (accept_eula|type_debug == 'bool' and not accept_eula)

- name: set default value for vault_password
  set_fact:
    vault_password: ''
  when: vault_password is undefined
  no_log: true

- name: set default value for secure_vault_password
  set_fact:
    secure_vault_password: ''
  when: secure_vault_password is undefined
  no_log: true

- name: check if the user use 2 passwords
  fail:
    msg: "You must provide either vault_password or secure_vault_password parameter"
  when: 
    - (vault_password != '')
    - (secure_vault_password != '')
  no_log: true  

- name: convert to securestring
  win_shell: |
    $secure_vault_password_object = ConvertTo-SecureString "{{ vault_password }}" -AsPlainText -Force
    $secure_vault_password_string = ConvertFrom-SecureString $secure_vault_password_object
    write-output $secure_vault_password_string
  register: secure_vault_password_string
  when: vault_password != ''
  no_log: true

- name: set varible for secured vault password
  set_fact:
    secure_vault_password: "{{ secure_vault_password_string.stdout_lines[0] }}"
    vault_password: ''
  when: secure_vault_password == ''
  no_log: true

- name: Check if PVWA is already installed (present in appwiz) (64-bit)
  win_reg_stat:
    path: HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall\{{ pvwa_guid }}
    name: Publisher
  register: pvwa_appwiz_info_64bit

- name: Check if PVWA is already installed (present in appwiz) (32-bit)
  win_reg_stat:
    path: HKLM:\Software\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\{{ pvwa_guid }}
    name: Publisher
  register: pvwa_appwiz_info_32bit

- name: Set fact if PVWA is already installed
  set_fact:
    pvwa_exists: true
  when: pvwa_appwiz_info_64bit.exists or pvwa_appwiz_info_32bit.exists

- name: Get PVWA Service Info
  win_service:
    name: CyberArk Scheduled Tasks
  register: service_info

- name: Set fact on hardening if correct user is running the service
  set_fact:
    pvwa_hardened: true
  when: service_info.exists and service_info.username == ".\\PVWAReportsUser"

- name: Check connection to PVWA to validate registration
  win_uri:
    url: "https://127.0.0.1/PasswordVault/api/server"
    validate_certs: no
    timeout: 60
  register: pvwa_server_info
  ignore_errors: yes

- set_fact:
    pvwa_registered: true
  when:
    - pvwa_server_info is defined
    - pvwa_server_info.status_code is defined
    - pvwa_server_info.status_code == 200
